#!/bin/bash

case "$2" in
  /proc/acpi/*/throttling)
      /bin/echo "$1" > "$2"
      ;;
esac

case "$2" in
  /proc/acpi/*/performance)
      /bin/echo "$1" > "$2"
      ;;
esac

case "$2" in
  /proc/acpi/*fan*)
      /bin/echo "$1" > "$2"
      ;;
esac

