// generated 2002/12/18 8:56:43 CET by thoma@Tiger.(none)
// using glademm V1.1.2a_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/thoma/Berlios/heatload/heatload.glade
// for gtk 1.2.10 and gtkmm 1.2.10
//
// Please modify the corresponding derived classes in ./src/WindowInfo.hh and./src/WindowInfo.cc

#ifndef _WINDOWINFO_GLADE_HH
#  define _WINDOWINFO_GLADE_HH

#include <gtk--/window.h>
#include <gtk--/label.h>
#include <gtk--/checkbutton.h>

class WindowInfo_glade : public Gtk::Window
{  
protected:
        
        class Gtk::Label *label_info;
        class Gtk::CheckButton *checkbutton_show;
        
        WindowInfo_glade();
        
        ~WindowInfo_glade();
private:
        virtual void on_button_close_clicked() = 0;
        virtual void on_checkbutton_show_toggled() = 0;
};
#endif
