// generated 2002/12/18 8:59:49 CET by thoma@Tiger.(none)
// using glademm V1.1.2a_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/thoma/Berlios/heatload/heatload.glade
// for gtk 1.2.10 and gtkmm 1.2.10
//
// Please modify the corresponding derived classes in ./src/WindowInfo.cc

#include "config.h"
#include "WindowInfo_glade.hh"
#include <gtk--/button.h>
#include <gtk--/table.h>

WindowInfo_glade::WindowInfo_glade(
) : Gtk::Window(GTK_WINDOW_TOPLEVEL)
{  
   
   Gtk::Window *WindowInfo = this;
   Gtk::Button *button_close = manage(new class Gtk::Button("Close"));
   label_info = manage(new class Gtk::Label("label4"));
   checkbutton_show = manage(new class Gtk::CheckButton("don't show this window again", 0, 0.5));
   
   Gtk::Table *table4 = manage(new class Gtk::Table(2, 2, false));
   button_close->set_flags(GTK_CAN_FOCUS);
   button_close->set_relief(GTK_RELIEF_NORMAL);
   label_info->set_alignment(7.45058e-09,0.5);
   label_info->set_padding(0,0);
   label_info->set_justify(GTK_JUSTIFY_LEFT);
   label_info->set_line_wrap(false);
   checkbutton_show->set_flags(GTK_CAN_FOCUS);
   checkbutton_show->set_mode(true);
   checkbutton_show->set_active(false);
   table4->set_row_spacings(0);
   table4->set_col_spacings(0);
   table4->attach(*button_close, 1, 2, 1, 2, GTK_FILL, 0, 0, 0);
   table4->attach(*label_info, 0, 2, 0, 1, GTK_SHRINK|GTK_FILL, GTK_SHRINK, 0, 0);
   table4->attach(*checkbutton_show, 0, 1, 1, 2, GTK_SHRINK|GTK_FILL, GTK_SHRINK, 0, 0);
   WindowInfo->set_title("Info");
   WindowInfo->set_modal(false);
   WindowInfo->set_position(GTK_WIN_POS_NONE);
   WindowInfo->set_policy(true, true, true);
   WindowInfo->add(*table4);
   button_close->show();
   label_info->show();
   checkbutton_show->show();
   table4->show();
   WindowInfo->show();
   button_close->clicked.connect(SigC::slot(this, &WindowInfo_glade::on_button_close_clicked));
   checkbutton_show->toggled.connect(SigC::slot(this, &WindowInfo_glade::on_checkbutton_show_toggled));
}

WindowInfo_glade::~WindowInfo_glade()
{  
}
